### ISSUE TITLE
build issue of SNOPT 7.6 on macOS 10.12.5 with Apple LLVM version 8.1.0

### ISSUE THREAD

**Issue by beesor** [snopt/snopt-interface#13]
when running ./configure of 
SNOPT 7.6 on macOS 10.12.5 with Apple LLVM version 8.1.0

the configure fails with the following error 

sed: confdefs.h: No such file or directory
configure: creating ./config.status
config.status: error: cannot find input file: `GNUmakefile.in'

on the same system using macports installed gcc 6.4 this does not occur.

**Comment by beesor** [comment]
this is just during configure. attached is the config.log when trying to run the following command: 

./configure --with-c-cpp

[config.log](https://github.com/snopt/snopt-interface/files/1734156/config.log)

**Comment by beesor** [comment]
The above error occurred on two Apple machines both running the same macOS and Apple Clang as the C/C++ compiler. I did check a third Apple machine same criteria as above, and the configure, build went fine; so something is different about the auto tools being used on the first two machines. Any ideas would be appreciated.

**Comment by gnowzil** [comment]
No Fortran compiler detected.   You probably don't have gfortran installed.  As far as I can tell this has nothing to do with clang.

**Comment by beesor** [comment]
gfortran was not on the path. re-installed with homebrew and now it is being found, but it appears from the config.log that fortran is still the issue. 

[config.log](https://github.com/snopt/snopt-interface/files/1734287/config.log)

**Comment by beesor** [comment]
yup, that solved the issue. thank you for the quick help!
