### ISSUE TITLE
getIntParameter, getRealParameter in C wrapper don't output value

### ISSUE THREAD

**Issue by jefesaurus** [snopt/snopt-interface#16]
Haven't actually tried this, but it looks like it [takes the parameter `opt` by value](https://github.com/snopt/snopt-interface/blob/76b166ecdf5c55a3289ce0f849d8d3d101954a22/src/snopt_cwrap.c#L234) and takes a reference internally, which should probably be passed in to make `opt` an out parameter.

**Comment by gnowzil** [comment]
fixed.  thank you!
