### ISSUE TITLE
neA for an unconstrained optimization problem

### ISSUE THREAD

**Issue by hongkai-dai** [snopt/snopt-interface#22]
I am trying to solve an unconstrained nonlinear optimization problem, using `snOptB` interface in snopt 7.5-1.4 (not SNOPT 7.6). When I call `setProblemSize` in `snopt_cwrap.h`, I set `ne` to 0, as I think my Jacobian matrix would be empty in this case.

I guess that `ne` the variable `neA` on top of page 35 Snopt User Guide 7 (http://www.ccom.ucsd.edu/~peg/papers/sndoc7.pdf)? And the doc says `neA > 0`. I guess I don't know why `neA` should be nonzero if the problem is unconstrained.

When I call `solveC` function, I received the following error
```
 ==============================
 S N O P T  7.5-1.4  (Dec 2015)
 ==============================

 SNMEMB EXIT 100 -- finished successfully
 SNMEMB INFO 104 -- memory requirements estimated

 XXX  Argument out of range:  neJ    =      0

 SNOPTC EXIT  90 -- input arguments out of range
 SNOPTC INFO  91 -- invalid input argument
```
I suppose `neJ` here is actually `ne`, the same as `neA`? Should `neJ = 0` for an unconstrained nonlinear problem?

**Comment by gnowzil** [comment]
SNOPT is a nonlinear constrained optimization solver.  If you want to solve an unconstrained problem, you have to define a dummy constraint with no bounds.

**Comment by hongkai-dai** [comment]
Thanks for the prompt reply! Much appreciated.

**Comment by hongkai-dai** [comment]
Ah sorry, it should be line 265 of `snopt_cwrap.cc`, not the header file.

**Comment by gnowzil** [comment]
Still doesn't match my files.

**Comment by gnowzil** [comment]
Regardless, I'm sure that line is to estimate workspace -- giving the max value of `negCon` will allocate more space than necessary, but otherwise won't do any harm.
