### ISSUE TITLE
Print to file, but not on the terminal

### ISSUE THREAD

**Issue by hongkai-dai** [snopt/snopt-interface#23]
Currently when I run `interfaces/cexamples/toyC` in snopt 7.5-1.4, I get a printout file `ToyC.out`, and also on the terminal where I launch `toyC` binary, it also print out snopt logs. How can I set SNOPT to only print to the file `TyoC.out`, but not to the terminal?

**Comment by gnowzil** [comment]
Set `summOn = 0` when you call `snInit`.  See https://ccom.ucsd.edu/~optimizers/usage/c/ for info.

**Comment by hongkai-dai** [comment]
Thanks! That works!
