### ISSUE TITLE
make Error :  '../src/snopt_wrapper.lo', needed by 'lib/libsnopt7_cpp.la'. 

### ISSUE THREAD

**Issue by kurosh-z** [snopt/snopt-interface#25]
Hi , 
after ../configure , I cannot make because of  this error:
![image](https://user-images.githubusercontent.com/32224317/45704161-777cc200-bb76-11e8-8689-bfa7007a7f58.png)

Any idea what might cause this ?

**Comment by gnowzil** [comment]
There was a mistake in the Makefile that only comes up if you build in another directory.  I've just pushed an update to fix this.  Let me know if it still doesn't work.

**Comment by kurosh-z** [comment]
Thank you for your reply . yes , that works now but for some reason I had to still export this final line to make it work !
export lsnopt7=$HOME/lib

![image](https://user-images.githubusercontent.com/32224317/45778650-74a6cd80-bc59-11e8-9eb9-30d651f0439a.png)
