### ISSUE TITLE
Snopt 7.7 evaluation library (c/Fortran) problems

### ISSUE THREAD

**Issue by darioizzo** [snopt/snopt-interface#27]
Here is what I get after having dl opened the c/fortran library I downloaded from  http://ccom.ucsd.edu/~optimizers/downloads/software/trial and called the solveA function.

Any known problem with those files?

  
```
==============================
    SNOPT  C interface  2.2.0   
 ==============================
 S N O P T  7.7.1    (Nov 2018)
 ==============================
 
 SNMEMA EXIT 100 -- finished successfully
 SNMEMA INFO 104 -- memory requirements estimated

 Trial version of SNOPT -- for evaluation or academic purposes only
At line 104 of file src/sn01res.f (unit = 10, file = '/home/dario/Install/snopt7)
Fortran runtime error: End of file

```

**Comment by gnowzil** [comment]
Try pointing to the license file directly, not the directory it's in.

**Comment by darioizzo** [comment]
Indeed, thanks for the quick reply. Stupid mistake from my side. It is also documented correctly on your web pages.
