### ISSUE TITLE
Specify SNOPT options that require string arguments

### ISSUE THREAD

**Issue by sanjeev-narayanaswamy** [snopt/snopt-interface#28]
Hi @gnowzil ,

I'm just wondering if it is possible to set SNOPT options that require string arguments through the C interface. For example, I am trying to set:

```
QPSolver QN
System information Yes
```
Could you please tell me if there is a function in [snopt_cwrap.h](https://github.com/snopt/snopt-interface/blob/master/include/snopt_cwrap.h) that would allow this?

Thanks for your help.

**Comment by gnowzil** [comment]
`setParameter`, `setIntParameter`, `setRealParameter` are the equivalent functions to the Fortran routines `snSet`, snSetI` and `snSetR` of SNOPT.

For all string setting, use `setParameter`.

**Comment by sanjeev-narayanaswamy** [comment]
Thanks a lot for your help @gnowzil, I really appreciate it.
