### ISSUE TITLE
problem during installing the lib

### ISSUE THREAD

**Issue by TrayfourYu** [snopt/snopt-interface#31]
I'm a new bird. And these ware some errors when I was  compiling and installing the project using those commands.

**1.aclocal
2.autoconf
3.automake --add-missing**

configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
automake: error: no 'Makefile.am' found for any configure output

**4../configure**
**5.make**

/usr/bin/ld: cannot find -lsnopt7
collect2: error: ld returned 1 exit status
Makefile:137: recipe for target 'lib/libsnopt7_c.la' failed
make: *** [lib/libsnopt7_c.la] Error 1

**6.make install**

/usr/bin/ld: cannot find -lsnopt7
collect2: error: ld returned 1 exit status
Makefile:134: recipe for target 'lib/libsnopt7_cpp.la' failed
make: *** [lib/libsnopt7_cpp.la] Error 1

I am really confuzed and hope someone can help me out. Tanks!

**Comment by gnowzil** [comment]
You most likely do not need to compile this library.  We provide compiled libraries from our website
https://ccom.ucsd.edu/~optimizers/downloads/
