### ISSUE TITLE
Setting nS when performing a warm start

### ISSUE THREAD

**Issue by dandezille** [snopt/snopt-interface#5]
The documentation states that for cold starts the value of nS need not be set, but for warm starts it should retain the value from the previous call.

Currently nS is declared within the solve function body and as such there is no way to set it, or for it to retain its value from the previous solve.

If the documentation is correct, it would seem that the C++ interface does not allow for warm starts as nS can not be set, is this correct?

Many thanks

**Comment by gnowzil** [comment]
It's actually okay if you don't set nS for a warm start.  The important info to pass in is x and hs, which give the initial point and the initial basis.  That will be enough for the warm start.

**Comment by dandezille** [comment]
Thanks a lot, that was the answer I was hoping for!
