### ISSUE TITLE
how to make sntoyA cpp example 

### ISSUE THREAD

**Issue by nedatym** [snopt/snopt-interface#6]
Hi,

I've proposed to run sntoya.cpp from cppexamples. I've generated a Makefile from Makefile.in, but when I do make, I have this error:
 No rule to make target `/snopt_wrapper.lo', needed by `lib/libsnopt7_c.la'.  Stop.

Can you please help me with this issue?

Thanks.
Neda

**Comment by gnowzil** [comment]
Can you try with the latest release?  I've updated configure and Makefile.

**Comment by salimoha** [comment]
Hi, I cannot make the C example working. I have the snopt working in python, but I need a cpp version. I am not able to run snoptA as well

**Comment by gnowzil** [comment]
You're getting the same error...?  It would be helpful if you provided more details.

(Also if unrelated to the original issue, it might be better to create a new one. Thanks.)

**Comment by salimoha** [comment]
I was wondering how I could make the executable examples in C or cpp? I want to use snopt as a solver in my cpp code. how can I use it in that way?

**Comment by gnowzil** [comment]
Is snoptProblem.hpp in the directory $SNOPT/include?

**Comment by salimoha** [comment]
yes. snopt.h  snoptProblem.hpp are included in the include folder
