### ISSUE TITLE
snJac not in the c interface.

### ISSUE THREAD

**Issue by darioizzo** [snopt/snopt-interface#9]
The routine snJac, to estimate the sparisty and the linear part of the problem, seems not to be available from the C interface. Am I missing something?

**Comment by gnowzil** [comment]
That is an oversight on my part.  Will add it asap.

**Comment by darioizzo** [comment]
oh, thanks!

**Comment by gnowzil** [comment]
snJac should be there now.  toyA in cexamples has been updated to call it.
